### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by airyland** [iseekr/x-influxdb#1]
+ [ ] query store to localStorage
+ [ ] group data into 24h
+ [ ] time range support today, yesterday,-ndays
